eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:9000/eureka/

spring:
  application:
    name: zuul


server:
  port: 9001

##  日志
logging:
  #config: classpath:logback.xml
  level:
    ROOT: INFO
    com:
      alibaba:
        druid: INFO
      zz:
        auth:
          server: DEBUG
zuul:
  host:
    max-per-route-connections: 60000
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId: auth
    union:
      path: /union/**
      sensitiveHeaders:
      serviceId: union
    authentication:
      path: /authentication/**
      sensitiveHeaders:
      serviceId: authentication
  add-proxy-headers: true
  sensitive-headers:

ribbon:
  ReadTimeout: 60000  # 单位毫秒数
  SocketTimeout: 60000

security:
  oauth2:
    client:
      client-id: client_2
      client-secret: $2a$10$ijOPEDarOjkdahi3xpslIu6.cMpBVqYWpbGTkCh0h7Kjt4.NWQwkK
      access-token-uri: http://localhost:9001/authentication/oauth/token
      user-authorization-uri: http://localhost:9001/authentication/oauth/authorize
    resource:
      user-info-uri: http://localhost:9001/authentication/user
      prefer-token-info: false
ignore:
  authUrls: /oauth/token,v2

jwt:
  jwtSecretKey: bGVjc2hvcF9qd3Rfc2VjcmV0X2tleQ==
info:
  app:
    name: app
    desc: app
